
### GET base
GET http://localhost:3000/

### GET user
GET http://localhost:3000/user/one
Content-Type: application/json

{
  "email": "###@gmail.com"
}

### PATCH user
PATCH http://localhost:3000/user/
Content-Type: application/json

{
  "email": ""
}

### POST user
POST http://localhost:3000/user
Content-Type: application/json

{
  "name" : "Dereck Silva",
  "email": "viniciusde3.reckc39@gmail.com",
  "password": ""
}