
### GET base
GET http://localhost:3000/

### GET user
GET http://localhost:3000/user/one
Content-Type: application/json

{
  "email": "###@gmail.com"
}

### PATCH user
PATCH http://localhost:3000/user/
Content-Type: application/json

{
  "email": ""
}